.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. UFO_qt test_UFO_qt
clean: FORCE
	$(MAKE) -C .. UFO_qt_clean test_UFO_qt_clean
check: FORCE
	$(MAKE) -C .. test_UFO_qt_check
UFO-qt UFO-qt.exe: FORCE
	 $(MAKE) -C .. UFO_qt
